defaults:
  - env_config: asos_config

exp_id: '036afc'
device: 'cuda:6'
runs: 751
batches: 10
setup_dict: False 
path: 'notebooks/constraints/ASOSFINAL_'

policy_list:
  mixed_uni: 
    _target_: AES.policies.linear.base_policy.LinearUniform
    name: "Mixed Uniform"
    type: "mixed"
  deconfounded_TS:
    _target_: AES.policies.linear.linear_ts.DeconfoundedTS
    name: "Deconfounded TS"
    toptwo: False
    n_samples: 10000
    type: "mixed" 
  deconfounded_toptwo_TS:
    _target_: AES.policies.linear.linear_ts.DeconfoundedTS
    name: "Deconfounded Top Two TS"
    toptwo: True 
    n_samples: 10000
    type: "mixed"
  mixed_rho1: 
    _target_: AES.policies.linear.linear_rho.LinearRho
    name: "Mixed Rho 005"
    mean: False
    lr: 0.05
    type: "mixed"
  mixed_rho2: 
    _target_: AES.policies.linear.linear_rho.LinearRho
    name: "Mixed Rho 01"
    mean: False
    lr: 0.1
    type: "mixed"
  mixed_rho5: 
    _target_: AES.policies.linear.linear_rho.LinearRho
    name: "Mixed Rho 015"
    mean: False
    lr: 0.15
    type: "mixed"
  mixed_rho6: 
    _target_: AES.policies.linear.linear_rho.LinearRho
    name: "Mixed Rho 025"
    mean: False
    lr: 0.25
    type: "mixed"
  mixed_rho10: 
    _target_: AES.policies.linear.linear_rho.LinearRho
    name: "Mixed Rho 05"
    mean: False
    lr: 0.5
    type: "mixed"
  mixed_rho11: 
    _target_: AES.policies.linear.linear_rho.LinearRho
    name: "Mixed Rho 1"
    mean: False
    lr: 1
    type: "mixed"

MDP:
  mixed_MDP: 
    _target_: AES.mdp.treatment_mdp.TreatmentPersonalMDP
    beta_0: None 
    sigma_0: None 
    n_arms: 10 
    s2: 0.1
    use_precision: False
    n_objs: 2


objective:
  _target_: 'AES.objectives.regret.constraint_best_arm'
  constraint_vals: 0